"""Socratic Learning - Continuous learning system for AI agents."""

from socratic_learning.analytics import MetricsCollector, PatternDetector
from socratic_learning.core import Interaction, Metric, Pattern, Recommendation
from socratic_learning.exceptions import (
    AggregationError,
    AnalyticsException,
    DataValidationException,
    ExportError,
    InsufficientDataError,
    InteractionException,
    InteractionFeedbackError,
    InteractionNotFoundError,
    InvalidFeedbackError,
    InvalidInteractionDataError,
    InvalidMetricDataError,
    InvalidPatternDataError,
    InvalidRecommendationStateError,
    InvalidSessionStateError,
    MetricsCalculationError,
    PatternDetectionError,
    PatternException,
    RecommendationException,
    RecommendationGenerationError,
    RecommendationNotFoundError,
    ReportGenerationError,
    SessionException,
    SessionNotFoundError,
    SocraticLearningException,
    StorageBackendError,
    StorageException,
    StorageNotFoundError,
    StorageOperationError,
)
from socratic_learning.storage import BaseLearningStore, SQLiteLearningStore
from socratic_learning.tracking import InteractionLogger, Session
from socratic_learning.integrations import LearningTool, SocraticLearningSkill

__version__ = "0.1.0"

__all__ = [
    "Interaction",
    "Pattern",
    "Metric",
    "Recommendation",
    "BaseLearningStore",
    "SQLiteLearningStore",
    "Session",
    "InteractionLogger",
    "MetricsCollector",
    "PatternDetector",
    "SocraticLearningSkill",
    "LearningTool",
    # Exceptions
    "SocraticLearningException",
    "StorageException",
    "StorageBackendError",
    "StorageOperationError",
    "StorageNotFoundError",
    "DataValidationException",
    "InvalidInteractionDataError",
    "InvalidFeedbackError",
    "InvalidMetricDataError",
    "InvalidPatternDataError",
    "InteractionException",
    "InteractionNotFoundError",
    "InteractionFeedbackError",
    "SessionException",
    "SessionNotFoundError",
    "InvalidSessionStateError",
    "PatternException",
    "PatternDetectionError",
    "InsufficientDataError",
    "RecommendationException",
    "RecommendationGenerationError",
    "RecommendationNotFoundError",
    "InvalidRecommendationStateError",
    "AnalyticsException",
    "MetricsCalculationError",
    "ReportGenerationError",
    "AggregationError",
    "ExportError",
]
